export const styleHeaderHome = {
  containerLabel: {
    height: 32,
    width: 76,
    borderWidth: 1,
    borderColor: '#B2BDCD',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    marginLeft: 24,
    marginRight: 3,
  },
  textLabel: {
    paddingTop: 8,
    paddingLeft: 8,
    paddingRight: 5,
    paddingBottom: 5,
    fontFamily: 'Roboto',
    fontWeight: 'normal',
    color: '#77869E',
  },
  containerDown: {
    width: 27,
    height: 32,
    backgroundColor: '#DADADA',
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconDown: {color: '#FFF', marginTop: 3, fontSize: 20},
  plus: {
    fontSize: 24,
    color: '#707378',
    marginRight: 26,
  },
  containerHeader: {height: 28, marginTop: 28, marginLeft: 24},
  textWeather: {
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontSize: 24,
    marginBottom: 14,
  },
  containerWT: {flexDirection: 'row', paddingRight: 10, marginTop: 8},
  icWt: {fontSize: 32, color: '#707378'},
  txtWT: {
    fontFamily: 'Roboto-Medium',
    marginLeft: 9,
    marginTop: 5,
  },
  ctnTemp: {flexDirection: 'row', paddingRight: 20},
  icTemp: {fontSize: 30, color: '#707378'},
  txtTemp: {
    fontFamily: 'Roboto-Medium',
    marginLeft: 2,
    marginTop: 10,
    fontSize: 18,
  },
  txtHumi: {
    fontFamily: 'Roboto-Medium',
    marginLeft: 9,
    marginTop: 5,
    fontSize: 18,
  },
  icExpand: {
    fontSize: 15,
    marginRight: 24,
    marginTop: 15,
    color: '#B2BDCD',
  },
};
